### ISSUE TITLE
Golang GitHub workflow action

### ISSUE THREAD

**Issue by 030** [030/n3dr#423]
**What would you like to be added**:
```
---
name: Golang
'on': push
jobs:
  mcaf-mcvs-golang-action:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: 030/mcaf-mcvs-golang-action@1-golangci-lint
        with:
          golang-unit-tests-exclusions: |-
            '\(cmd\/n3dr\|internal\/app\/n3dr\/\(goswagger\|n3drtest\)\)'
```
**Why is this needed**:
