### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by 030** [030/n3dr#49]
**What would you like to be added**:

- docker-compose

**Why is this needed**:

- some variables are hard to set on Windows

**Comment by 030** [comment]
```
version: '3.7'
services:
  n3dr:
    image: utrecht/n3dr:2.2.1
    volumes:
      - ~/.n3dr.yaml:/home/n3dr/.n3dr.yaml
      - ~/2019-05-20-nexus-fqdn:/download
    environment:
      - HTTPS_PROXY=some-proxy
    command: repositories -n some-nexus -u admin -d
```
